name: Ping Bot Every 13 Minutes

on:
  schedule:
    - cron: '0,13,26,39,50 * * * *'
  workflow_dispatch:

concurrency:
  group: ping-bot
  cancel-in-progress: true

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Webserver Using Secret
        run: curl -s ${{ secrets.PING_URL }}
