name: Ping Bot Every 13 Minutes

on:
  schedule:
    - cron: '0,13,26,39,50 * * * *'
  workflow_dispatch:  # Optional: allows manual run

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Webserver
        run: curl -s https://ap-rgukt.onrender.com
