name: Ping Render Webserver Every 13 Minutes

on:
  schedule:
    - cron: "*/13 * * * *"  # Every 13 minutes
  workflow_dispatch:  # Optional manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send GET request to Render
        run: |
          curl -s -o /dev/null -w "%{http_code}" https://dashboard.render.com/web/srv-d156so7fte5s738s07e0
